# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 2048

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - foreman
  pillars:
    top.sls:
      base:
        "*":
          - foreman

platforms:
  - name: bento/debian-8.8

suites:
  - name: default
    provisioner:
      pillars:
        foreman.sls:
          foreman:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        foreman.sls: pillar-custom.sls
